import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { formatCurrency, formatDate } from '../utils';

/**
 * Generate and share a PDF for an invoice or quote.
 * Uses expo-print to render HTML to PDF, then expo-sharing to share/save.
 */

function buildLineItemsHTML(lineItems) {
  const rows = (lineItems || [])
    .filter((li) => li.type !== 'text')
    .map(
      (li) => `
      <tr>
        <td style="padding:8px 12px;border-bottom:1px solid #2D3B4E;">${li.name || li.description || ''}</td>
        <td style="padding:8px 12px;border-bottom:1px solid #2D3B4E;text-align:center;">${li.qty || 0}</td>
        <td style="padding:8px 12px;border-bottom:1px solid #2D3B4E;text-align:right;">${formatCurrency((li.price || 0) / 100)}</td>
        <td style="padding:8px 12px;border-bottom:1px solid #2D3B4E;text-align:right;">${formatCurrency(((li.qty || 0) * (li.price || 0)) / 100)}</td>
      </tr>`,
    )
    .join('');

  return `
    <table style="width:100%;border-collapse:collapse;margin:20px 0;">
      <thead>
        <tr style="background:#0EA5A0;">
          <th style="padding:10px 12px;text-align:left;color:#fff;font-size:12px;">Description</th>
          <th style="padding:10px 12px;text-align:center;color:#fff;font-size:12px;">Qty</th>
          <th style="padding:10px 12px;text-align:right;color:#fff;font-size:12px;">Price</th>
          <th style="padding:10px 12px;text-align:right;color:#fff;font-size:12px;">Total</th>
        </tr>
      </thead>
      <tbody>${rows}</tbody>
    </table>`;
}

function buildTotalsHTML(totals, taxRate) {
  if (!totals) return '';
  const sub = totals.subtotal ?? totals.subtotalBeforeDiscount ?? 0;
  const tax = totals.tax ?? totals.taxAmount ?? 0;
  const total = totals.total ?? 0;

  let html = `
    <div style="text-align:right;margin:10px 0;">
      <div style="margin-bottom:4px;"><span style="color:#6B7F96;margin-right:24px;">Subtotal</span> ${formatCurrency(sub / 100)}</div>`;
  if (tax > 0) {
    html += `<div style="margin-bottom:4px;"><span style="color:#6B7F96;margin-right:24px;">Tax${taxRate ? ` (${taxRate}%)` : ''}</span> ${formatCurrency(tax / 100)}</div>`;
  }
  html += `<div style="font-size:18px;font-weight:700;color:#0EA5A0;margin-top:8px;"><span style="color:#6B7F96;margin-right:24px;">Total</span> ${formatCurrency(total / 100)}</div>
    </div>`;
  return html;
}

function wrapHTML(title, body) {
  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width,initial-scale=1" />
  <style>
    * { margin:0; padding:0; box-sizing:border-box; }
    body { font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif; color:#1A2332; padding:40px; font-size:14px; }
    .header { display:flex; justify-content:space-between; align-items:flex-start; margin-bottom:32px; }
    .doc-title { font-size:28px; font-weight:700; color:#0EA5A0; }
    .meta { color:#6B7F96; font-size:12px; line-height:1.6; }
    .section { margin-bottom:20px; }
    .section-label { font-size:11px; font-weight:600; letter-spacing:1.5px; text-transform:uppercase; color:#6B7F96; margin-bottom:8px; }
    .notes { background:#F8FAFC; border-radius:8px; padding:12px; font-size:13px; line-height:1.5; color:#374151; }
    .footer { margin-top:40px; text-align:center; color:#6B7F96; font-size:11px; border-top:1px solid #E5E7EB; padding-top:16px; }
  </style>
</head>
<body>
  ${body}
  <div class="footer">Generated by Scaffld &middot; ${new Date().toLocaleDateString()}</div>
</body>
</html>`;
}

/**
 * Generate an invoice PDF and open the share sheet.
 */
export async function shareInvoicePDF(invoice, client, company) {
  const clientName = client?.name || 'Client';
  const companyBlock = [company?.name, company?.address, company?.phone, company?.email].filter(Boolean).join('<br/>');

  const totalPaid = (invoice.payments || []).reduce((s, p) => s + Number(p.amount || 0), 0);
  const amountDue = Math.max(0, (invoice.total || 0) - totalPaid);

  const paymentsHTML = (invoice.payments || []).length > 0
    ? `<div class="section">
        <div class="section-label">Payments</div>
        ${invoice.payments.map((p) => `<div style="display:flex;justify-content:space-between;padding:4px 0;"><span>${p.method || 'Payment'} — ${formatDate(p.createdAt)}</span><span style="color:#22C55E;">-${formatCurrency((p.amount || 0) / 100)}</span></div>`).join('')}
        <div style="display:flex;justify-content:space-between;padding:8px 0;font-weight:700;border-top:1px solid #E5E7EB;margin-top:4px;"><span>Amount Due</span><span style="color:${amountDue > 0 ? '#F7845E' : '#0EA5A0'};">${formatCurrency(amountDue / 100)}</span></div>
       </div>`
    : '';

  const body = `
    <div class="header">
      <div>
        <div class="doc-title">INVOICE</div>
        <div class="meta" style="margin-top:8px;">
          #${invoice.invoiceNumber || 'N/A'}<br/>
          Issued: ${formatDate(invoice.issueDate || invoice.createdAt)}<br/>
          Due: ${formatDate(invoice.dueDate)}<br/>
          Status: ${invoice.status || 'Draft'}
        </div>
      </div>
      <div class="meta" style="text-align:right;">${companyBlock}</div>
    </div>

    <div class="section">
      <div class="section-label">Bill To</div>
      <div><strong>${clientName}</strong></div>
      <div class="meta">${[client?.email, client?.phone, client?.address].filter(Boolean).join('<br/>')}</div>
    </div>

    ${buildLineItemsHTML(invoice.lineItems)}
    ${buildTotalsHTML({ subtotal: invoice.subtotal || invoice.total, tax: invoice.tax, total: invoice.total }, invoice.taxRate)}
    ${paymentsHTML}
    ${invoice.notes ? `<div class="section"><div class="section-label">Notes</div><div class="notes">${invoice.notes}</div></div>` : ''}`;

  const html = wrapHTML('Invoice', body);
  const filename = `Invoice_${invoice.invoiceNumber || invoiceId(invoice)}.pdf`;
  await generateAndShare(html, filename);
}

/**
 * Generate a quote PDF and open the share sheet.
 */
export async function shareQuotePDF(quote, client, company, totals) {
  const clientName = client?.name || 'Client';
  const companyBlock = [company?.name, company?.address, company?.phone, company?.email].filter(Boolean).join('<br/>');

  const body = `
    <div class="header">
      <div>
        <div class="doc-title">QUOTE</div>
        <div class="meta" style="margin-top:8px;">
          #${quote.quoteNumber || 'N/A'}<br/>
          Created: ${formatDate(quote.createdAt)}<br/>
          ${quote.sentAt ? `Sent: ${formatDate(quote.sentAt)}<br/>` : ''}
          Status: ${quote.status || 'Draft'}
        </div>
      </div>
      <div class="meta" style="text-align:right;">${companyBlock}</div>
    </div>

    <div class="section">
      <div style="font-size:20px;font-weight:600;margin-bottom:4px;">${quote.title || 'Untitled Quote'}</div>
      <div><strong>${clientName}</strong></div>
      <div class="meta">${[client?.email, client?.phone, client?.address].filter(Boolean).join('<br/>')}</div>
    </div>

    ${buildLineItemsHTML(quote.lineItems)}
    ${buildTotalsHTML(totals, quote.taxRate)}
    ${quote.clientMessage ? `<div class="section"><div class="section-label">Message to Client</div><div class="notes">${quote.clientMessage}</div></div>` : ''}`;

  const html = wrapHTML('Quote', body);
  const filename = `Quote_${quote.quoteNumber || shortId(quote)}.pdf`;
  await generateAndShare(html, filename);
}

async function generateAndShare(html, filename) {
  const { uri } = await Print.printToFileAsync({ html });
  await Sharing.shareAsync(uri, {
    mimeType: 'application/pdf',
    dialogTitle: `Share ${filename}`,
    UTI: 'com.adobe.pdf',
  });
}

function invoiceId(inv) { return inv.id?.substring(0, 8) || 'unknown'; }
function shortId(doc) { return doc.id?.substring(0, 8) || 'unknown'; }
